### ISSUE TITLE
Not working...

### ISSUE THREAD

**Issue by xp0inter** [zyantific/IDASkins#71]
Hi, there is a problem for me. When I try to change the skin, it comes out a UnicodeDecodeError: 

[IDASkins] v2.1.0 by athre0z (zyantific.com) loaded!
E:\Program Files\IDA 7.2\plugins\idaskins.py: Traceback (most recent call last):
  File "E:/Program Files/IDA 7.2/plugins/idaskins.py", line 5, in PLUGIN_ENTRY
    return IdaSkinsPlugin(*args, **kwargs)
  File "E:/Program Files/IDA 7.2/plugins\idaskins\plugin.py", line 86, in __init__
    self.apply_stylesheet_from_settings()
  File "E:/Program Files/IDA 7.2/plugins\idaskins\plugin.py", line 146, in apply_stylesheet_from_settings
    self.apply_stylesheet(abs_theme_dir, manifest)
  File "E:/Program Files/IDA 7.2/plugins\idaskins\plugin.py", line 123, in apply_stylesheet
    qss = self.preprocess_stylesheet(qss, abs_theme_dir)
  File "E:/Program Files/IDA 7.2/plugins\idaskins\plugin.py", line 107, in preprocess_stylesheet
    qss = replace_keyword(qss, 'DISASSEMBLY', 'disas')
  File "E:/Program Files/IDA 7.2/plugins\idaskins\plugin.py", line 100, in replace_keyword
    x = x.replace(prefix + 'FAMILY>', cfg.family)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 0: ordinal not in range(128)

--------------------------------------

IDA pro: 7.2
Windows 7 sp1 
Python 2.7.18
Default language: Chinese

---------------------------------------

**Comment by xp0inter** [comment]
Oh, problem solved, the font name has Chinese Unicode. So I changed another font, and works well
